### ISSUE TITLE
タブの表記

### ISSUE THREAD

**Issue by friend1ws** [Genomon-Project/genomon-docs#4]
MacのSafariで開くと、ブラウザのタブ上の文が

「The Zen of Cancer Genome Sequence Analysis --- Genomon 0.1.0 ドキュメント」

となる。ちなみに、Google Chromeでは目立たない。他はわからない。

**Comment by aokad** [comment]
対応しました。
バージョンアップの際はconf.pyの `version` と `release` の変更も必要。
